// <auto-generated />
namespace TravelProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TourcityImage_mapLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TourcityImage_mapLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "202410271459369_TourcityImage_mapLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
